name: Android Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version tag (e.g., v2.1.0)"
        required: true
      submit_to_play_store:
        type: boolean
        description: "Submit to Google Play Store (internal track)"
        default: false

jobs:
  build_production:
    name: Build Production AAB
    type: build
    params:
      platform: android
      profile: production

  e2e_validation:
    name: E2E Validation
    needs: [build_production]
    type: maestro
    params:
      build_id: ${{ needs.build_production.outputs.build_id }}
      flow_path:
        - '.maestro/flows/smoke-test.yaml'
        - '.maestro/flows/main-menu.yaml'
        - '.maestro/flows/start-game.yaml'

  submit_play_store:
    name: Submit to Play Store
    needs: [build_production, e2e_validation]
    if: ${{ inputs.submit_to_play_store == true }}
    type: submit
    params:
      build_id: ${{ needs.build_production.outputs.build_id }}
