name: 'Setup Android SDK'
description: 'Set up Android SDK, Java, and Gradle for building APKs'

inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '21'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407  # v3.2.2

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses
      shell: bash

    - name: Install Android SDK components
      run: sdkmanager "platform-tools" "platforms;android-35" "build-tools;34.0.0"
      shell: bash
